import DocsLayout from "@/components/DocsLayout";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Search } from "lucide-react";
import { useState } from "react";

interface GlossaryTerm {
  term: string;
  definition: string;
  category: string;
}

const glossaryTerms: GlossaryTerm[] = [
  {
    term: "ERC-4626",
    definition: "A standard interface for tokenized vaults. Defines a common API for vaults that accept deposits of a single underlying ERC-20 token and issue shares in return. Octant Funding Vaults are ERC-4626 compliant.",
    category: "Standards"
  },
  {
    term: "Funding Vault",
    definition: "An ERC-4626-compliant smart contract that accepts deposits, deploys capital to yield strategies, and directs generated yield to a donation address while preserving the depositor's principal.",
    category: "Core Components"
  },
  {
    term: "Yield Donating Strategy (YDS)",
    definition: "A strategy that accepts a single ERC-20 token (like USDC) and donates profits to a donation address. When the strategy reports profit, new shares are minted and sent to the donation address. On loss, shares are burned.",
    category: "Strategies"
  },
  {
    term: "Yield Skimming Strategy (YSS)",
    definition: "A strategy that holds yield-bearing tokens (like stETH or rETH) directly and donates their exchange-rate appreciation. Uses a 'dragon buffer' mechanism to handle value fluctuations.",
    category: "Strategies"
  },
  {
    term: "Principal",
    definition: "The original amount of capital deposited into a Funding Vault. In Octant v2, the principal is preserved and never distributed—only the yield generated from the principal is donated.",
    category: "Financial Terms"
  },
  {
    term: "Yield",
    definition: "The profit or returns generated by deploying capital into DeFi strategies. In Octant, yield is automatically directed to the donation address rather than accruing to the depositor.",
    category: "Financial Terms"
  },
  {
    term: "Donation Address",
    definition: "The recipient address that receives newly minted shares representing yield. Can be an EOA, multisig wallet, Payment Splitter, or Allocation Mechanism contract.",
    category: "Core Components"
  },
  {
    term: "Payment Splitter",
    definition: "A smart contract that distributes received funds to multiple predefined recipients based on percentage allocations (e.g., 20% operations, 30% treasury, 50% allocation mechanism).",
    category: "Core Components"
  },
  {
    term: "Allocation Mechanism",
    definition: "Smart contracts that implement various fund allocation models, allowing communities to vote or decide how funds should be distributed to ecosystem projects.",
    category: "Core Components"
  },
  {
    term: "Tokenized Allocation Mechanism (TAM)",
    definition: "An on-chain allocation mechanism with defined lifecycle stages (register, propose, vote, finalize, queue, redeem). Examples include Quadratic Funding and Quadratic Voting.",
    category: "Core Components"
  },
  {
    term: "Quadratic Funding (QF)",
    definition: "An allocation mechanism that matches individual contributions with community funds using a quadratic formula. Prioritizes projects with broad support over those with few large donors.",
    category: "Allocation Models"
  },
  {
    term: "Quadratic Voting (QV)",
    definition: "A voting mechanism where the cost of each additional vote increases quadratically. Prevents vote concentration and encourages broader participation.",
    category: "Allocation Models"
  },
  {
    term: "Dragon Buffer",
    definition: "A mechanism in Yield Skimming Strategies that handles temporary value decreases in yield-bearing tokens. Prevents unnecessary share burning during normal market fluctuations.",
    category: "Strategies"
  },
  {
    term: "Dragon Vault",
    definition: "A Funding Vault integrated with Safe multisig wallets, designed for large organizations and treasuries. Provides enhanced security and governance controls.",
    category: "Vault Types"
  },
  {
    term: "Collective Funding Vault",
    definition: "A Funding Vault that pools capital from multiple participants, making ecosystem funding accessible for smaller communities and individuals.",
    category: "Vault Types"
  },
  {
    term: "Locked Vault",
    definition: "A vault type that requires a cooldown period before withdrawals. Users must initiate a 'ragequit' and wait before accessing their funds.",
    category: "Vault Types"
  },
  {
    term: "Ragequit",
    definition: "A mechanism that allows users to withdraw from Locked Vaults by initiating a cooldown period. Provides an exit option while maintaining vault stability.",
    category: "Mechanisms"
  },
  {
    term: "Keeper",
    definition: "A network participant who monitors strategy performance and triggers harvest & report functions. Keepers are incentivized through gas refunds and optional performance fees.",
    category: "Roles"
  },
  {
    term: "Strategy Report",
    definition: "A function call that calculates profit/loss, mints or burns shares accordingly, and updates the vault's accounting. Triggered by keepers.",
    category: "Operations"
  },
  {
    term: "Harvest",
    definition: "The process of collecting yield from a DeFi protocol (e.g., claiming rewards, compounding interest) and reporting it to the vault.",
    category: "Operations"
  },
  {
    term: "Share-to-Asset Ratio",
    definition: "The ratio between vault shares and underlying assets. Octant prioritizes maintaining a 1:1 ratio to preserve principal value.",
    category: "Financial Terms"
  },
  {
    term: "Multi-Strategy Vault",
    definition: "A vault that deploys capital across multiple yield strategies simultaneously. Enables diversification, risk management, and automated rebalancing.",
    category: "Vault Types"
  },
  {
    term: "Strategy Queue",
    definition: "An ordered list of strategies in a multi-strategy vault. Determines the priority for capital allocation and withdrawal.",
    category: "Multi-Strategy"
  },
  {
    term: "Debt Management",
    definition: "The process of allocating and rebalancing capital across strategies in a multi-strategy vault. Includes setting maximum debt ratios and updating allocations.",
    category: "Multi-Strategy"
  },
  {
    term: "Max Debt",
    definition: "The maximum amount of capital that can be allocated to a specific strategy. Used to limit exposure and manage risk.",
    category: "Multi-Strategy"
  },
  {
    term: "Community Staking",
    definition: "Optional token-staking mechanisms where community members stake ecosystem tokens to earn rewards and participate in funding allocation decisions.",
    category: "Governance"
  },
  {
    term: "Dragon Token",
    definition: "ERC-20 native community tokens used in Community Staking contracts for earning rewards and participating in allocation decisions.",
    category: "Tokens"
  },
  {
    term: "Yield-Donating Token",
    definition: "The ERC-4626 share token issued by a Funding Vault. Represents the depositor's principal and can be redeemed 1:1 for the underlying asset.",
    category: "Tokens"
  },
  {
    term: "Safe Linear Allowance Module",
    definition: "A Safe integration that allows users to set up linear token transfers to donation addresses over time. Enables automated recurring donations.",
    category: "Integrations"
  },
  {
    term: "OpEx (Operational Expenses)",
    definition: "A portion of yield claimed by capital providers to cover operational costs. Typically configured as a percentage in the Payment Splitter.",
    category: "Financial Terms"
  },
  {
    term: "Credible Neutrality",
    definition: "A design principle where the protocol doesn't prescribe what to fund, only how to fund. Ensures fairness and prevents bias in allocation decisions.",
    category: "Design Principles"
  },
  {
    term: "Capital Preservation",
    definition: "A core principle of Octant v2 where deposited principal is never distributed. Only generated yield flows to funding mechanisms.",
    category: "Design Principles"
  },
  {
    term: "Composability",
    definition: "The ability to integrate with other DeFi protocols and standards. Octant uses ERC-4626, supports Safe multisig, and interoperates with Aave, Morpho, etc.",
    category: "Design Principles"
  },
  {
    term: "Alpha Parameter (α)",
    definition: "A configurable parameter in Quadratic Funding mechanisms that adjusts the matching formula. Higher α values increase the matching amount.",
    category: "Allocation Models"
  },
  {
    term: "Hook",
    definition: "A customizable function in Allocation Mechanisms that executes at specific lifecycle stages (e.g., beforeSignupHook, processVoteHook). Enables custom logic.",
    category: "Development"
  },
  {
    term: "Base Strategy",
    definition: "The foundational smart contract that custom strategies inherit from. Provides common functionality like health checks, role management, and reporting.",
    category: "Development"
  },
  {
    term: "Health Check",
    definition: "A safety mechanism that validates strategy performance before finalizing reports. Prevents execution of reports that would harm the vault.",
    category: "Security"
  },
  {
    term: "Emergency Admin",
    definition: "A role with permissions to pause strategies or execute emergency withdrawals in case of security incidents.",
    category: "Roles"
  },
  {
    term: "Management Role",
    definition: "A role with permissions to configure strategy parameters, update donation addresses, and manage vault settings.",
    category: "Roles"
  }
];

export default function Glossary() {
  const [searchQuery, setSearchQuery] = useState("");

  const filteredTerms = glossaryTerms.filter(term =>
    term.term.toLowerCase().includes(searchQuery.toLowerCase()) ||
    term.definition.toLowerCase().includes(searchQuery.toLowerCase()) ||
    term.category.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const categories = Array.from(new Set(glossaryTerms.map(t => t.category))).sort();

  return (
    <DocsLayout>
      <div className="space-y-8">
        {/* Header */}
        <div>
          <Badge className="mb-4 bg-primary/10 text-primary border-primary/20">
            Reference
          </Badge>
          <h1 className="text-5xl font-bold mb-4">
            Glossary
          </h1>
          <p className="text-xl text-muted-foreground leading-relaxed">
            Comprehensive definitions of key terms and concepts in Octant v2
          </p>
        </div>

        {/* Search */}
        <div className="relative max-w-2xl">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
          <Input
            type="search"
            placeholder="Search terms, definitions, or categories..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-12 h-12 text-lg bg-muted/50 border-border/50"
          />
        </div>

        {/* Stats */}
        <div className="flex gap-4 text-sm text-muted-foreground">
          <span>{filteredTerms.length} terms</span>
          <span>•</span>
          <span>{categories.length} categories</span>
        </div>

        {/* Terms by Category */}
        <div className="space-y-8">
          {categories.map(category => {
            const categoryTerms = filteredTerms.filter(t => t.category === category);
            if (categoryTerms.length === 0) return null;

            return (
              <div key={category}>
                <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
                  <Badge variant="outline" className="text-base">
                    {category}
                  </Badge>
                  <span className="text-sm text-muted-foreground font-normal">
                    {categoryTerms.length} {categoryTerms.length === 1 ? 'term' : 'terms'}
                  </span>
                </h2>
                
                <div className="space-y-4">
                  {categoryTerms.map(({ term, definition }) => (
                    <Card key={term} className="p-5 border-border/50 hover:border-primary/30 transition-colors">
                      <h3 className="text-lg font-bold mb-2 text-primary">
                        {term}
                      </h3>
                      <p className="text-foreground/80 leading-relaxed">
                        {definition}
                      </p>
                    </Card>
                  ))}
                </div>
              </div>
            );
          })}
        </div>

        {/* No Results */}
        {filteredTerms.length === 0 && (
          <Card className="p-12 text-center border-dashed">
            <p className="text-lg text-muted-foreground">
              No terms found matching "<strong>{searchQuery}</strong>"
            </p>
            <p className="text-sm text-muted-foreground mt-2">
              Try searching for different keywords or browse all categories
            </p>
          </Card>
        )}
      </div>
    </DocsLayout>
  );
}
